# Basic Site Settings
locale: "en-US"
title: "Youssef Ateya's Personal Website"
description: "Professional website for Youssef Ateya, a Computer Science major at the University of Houston."
url: "https://joeamroo.github.io/youssef-formal-website"
baseurl: "" 
repository: "joeamroo/youssef-formal-website"

# Author Profile
author:
  name: "Youssef Ateya"
  bio: "Computer Science major with a minor in Math at the University of Houston."
  location: "Houston, TX"
  email: "youssefamrzagazig@gmail.com"
  linkedin: "https://www.linkedin.com/in/youssef-ateya"
  github: "joeamroo"

# Google Analytics
google_analytics: "G-V2C77HD88F"

# Social Links
social:
  links:
    - "https://github.com/joeamroo"
    - "https://www.linkedin.com/in/youssef-ateya"

# Include & Exclude
include:
  - .htaccess
  - _pages
  - files
exclude:
  - node_modules
  - vendor

# Conversion
markdown: kramdown
highlighter: rouge
